[package]
name = "gix-git-perf-test"
version = "0.1.0"
edition = "2021"

[dependencies]
git2 = "0.16.1"
gix = "0.43.1"
anyhow = "1.0.70"
gix-object = "0.28.0"

[dependencies.clap]
version = "4.2.1"
features = ["derive"]
